name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    if: >
      github.event_name == 'push' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: suhas4445/guestbook-go:latest
